name: Build Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++

    env:
      V: 1
      BAN_WARN: 1

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Add 32-bit repo
      run: |
        sudo dpkg --add-architecture i386;
    - name: Update repo
      run: |
        sudo apt-get update --fix-missing -y;
    - name: Install tools
      run: |
        sudo apt-get install -y clang gcc g++ make libc6-dev-i386 gcc-multilib \
        g++-multilib libgtk-3-common libgtk-3-dev libgtk-3-common:i386 \
        libgtk-3-dev:i386 gir1.2-gtk-3.0:i386 libatk-bridge2.0-dev:i386 \
        libatk1.0-dev:i386 libcairo2-dev:i386 libgdk-pixbuf2.0-dev:i386 \
        libglib2.0-dev:i386 libpango1.0-dev:i386 dconf-gsettings-backend:i386 \
        libgtk-3-0:i386 libglib2.0-0:i386 libdconf1:i386 gir1.2-atk-1.0:i386 \
        gir1.2-freedesktop:i386 gir1.2-gdkpixbuf-2.0:i386 gir1.2-glib-2.0:i386 \
        gir1.2-pango-1.0:i386 libatk-bridge2.0-0:i386 libatspi2.0-dev:i386 \
        libatk1.0-0:i386 gir1.2-atk-1.0:i386 libcairo-gobject2:i386 \
        libgdk-pixbuf2.0-0:i386 gir1.2-gdkpixbuf-2.0:i386 libglib2.0-0:i386 \
        libmount-dev:i386 libselinux1-dev:i386 libatk-bridge2.0-0:i386 \
        libatk1.0-0:i386 libcairo-gobject2:i386 libcolord2:i386 \
        libgdk-pixbuf2.0-0:i386 libglib2.0-0:i386 libharfbuzz0b:i386 \
        libjson-glib-1.0-0:i386 libpango-1.0-0:i386 libpangocairo-1.0-0:i386 \
        libpangoft2-1.0-0:i386 librest-0.7-0:i386 gir1.2-pango-1.0:i386 \
        libharfbuzz-dev:i386 libpango-1.0-0:i386 libpangocairo-1.0-0:i386 \
        libpangoft2-1.0-0:i386 libpangoxft-1.0-0:i386 libmount1:i386 \
        libselinux1:i386 libmount1:i386 libselinux1:i386 libpcre2-dev:i386 \
        libatk-bridge2.0-dev libatk1.0-dev libcairo2-dev libgdk-pixbuf2.0-dev \
        libglib2.0-dev libpango1.0-dev libpcre2-8-0:i386 libpcre2-posix2:i386 \
        libpcre2-8-0:i386  openssl \
        dconf-service:i386 \
        dconf-service:i386 \
        libatk-bridge2.0-0 \
        libatspi2.0-dev \
        libatk1.0-0 \
        gir1.2-atk-1.0 \
        pkg-config \
        pkg-config:i386 \
        libdbus-1-dev:i386 \
        libcairo2:i386 \
        libcairo2 \
        libcairo-gobject2 \
        libcairo-script-interpreter2 \
        libfontconfig1-dev \
        libcairo2:i386 \
        libcairo-script-interpreter2:i386 \
        libfontconfig1-dev:i386 \
        libgssapi-krb5-2 \
        shared-mime-info:i386 \
        libgdk-pixbuf2.0-0 \
        gir1.2-gdkpixbuf-2.0 \
        shared-mime-info \
        shared-mime-info:i386 \
        libglib2.0-dev-bin \
        pkg-config \
        libglib2.0-dev-bin:i386 \
        pkg-config:i386 \
        adwaita-icon-theme:i386 \
        shared-mime-info:i386 \
        libcairo2:i386 \
        libcups2:i386 \
        libfontconfig1:i386 \
        dconf-gsettings-backend \
        gsettings-backend \
        gir1.2-gtk-3.0 \
        libfontconfig1-dev \
        libwayland-dev \
        pkg-config \
        dconf-gsettings-backend \
        gsettings-backend \
        libgtk-3-0 \
        libfontconfig1-dev:i386 \
        libwayland-dev:i386 \
        pkg-config:i386 \
        libharfbuzz-icu0:i386 \
        libicu-dev:i386 \
        libgd3 \
        libxml2 \
        libxslt1.1 \
        gir1.2-pango-1.0 \
        libfontconfig1-dev \
        libharfbuzz-dev \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libpangoft2-1.0-0 \
        libpangoxft-1.0-0 \
        libthai-dev \
        libxft-dev \
        pango1.0-tools \
        pkg-config \
        libfontconfig1-dev:i386 \
        libthai-dev:i386 \
        libxft-dev:i386 \
        pango1.0-tools:i386 \
        pkg-config:i386 \
        libcairo2:i386 \
        libfontconfig1:i386 \
        libfontconfig1:i386 \
        libfontconfig1:i386 \
        libxft2:i386 \
        libpcre2-8-0 \
        libpcre2-8-0:i386 \
        libpcre2-dev \
        libpcre2-16-0:i386 \
        libpcre2-32-0:i386 \
        Breaks: \
        libpcre2-posix2 \
        libpcre2-posix2:i386 \
        libsoup-gnome2.4-1:i386 \
        libsoup2.4-1:i386 \
        libxml2:i386 \
        libgssapi-krb5-2 \
        login;
        sudo apt-get clean -y;
        sudo apt-get install -f;
        sudo dpkg --configure -a;

    - name: Show tools version
      run: |
        ${{matrix.cc}} --version;
        ${{matrix.cxx}} --version;
        make --version;
    - name: Build (Debug Mode)
      run: |
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}};
        make -j$(nproc) DEBUG_MODE=1;
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --gui;
        make -j$(nproc) DEBUG_MODE=1;
    - name: Build
      run: |
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}};
        make -j$(nproc);
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --gui;
        make -j$(nproc);
    - name: Build 32-bit (Debug Mode)
      run: |
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --32-bit;
        make -j$(nproc) DEBUG_MODE=1;
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --32-bit --gui;
        make -j$(nproc) DEBUG_MODE=1;
    - name: Build 32-bit
      run: |
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --32-bit;
        make -j$(nproc);
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --32-bit --gui;
        make -j$(nproc);
