name: Build Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++

    env:
      V: 1
      BAN_WARN: 1

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Add 32-bit repo
      run: |
        sudo dpkg --add-architecture i386;
    - name: Update repo
      run: |
        sudo apt-get update --fix-missing -y;
    - name: Install tools
      run: |
        sudo apt-get install -y clang gcc g++ make libc6-dev-i386 gcc-multilib \
        g++-multilib libgtk-3-common libgtk-3-dev libgtk-3-common:i386 \
        libgtk-3-dev:i386 gir1.2-gtk-3.0:i386 libatk-bridge2.0-dev:i386 \
        libatk1.0-dev:i386 libcairo2-dev:i386 libgdk-pixbuf2.0-dev:i386 \
        libglib2.0-dev:i386 libpango1.0-dev:i386 dconf-gsettings-backend:i386 \
        libgtk-3-0:i386 libglib2.0-0:i386 libdconf1:i386 gir1.2-atk-1.0:i386 \
        gir1.2-freedesktop:i386 gir1.2-gdkpixbuf-2.0:i386 gir1.2-glib-2.0:i386 \
        gir1.2-pango-1.0:i386 libatk-bridge2.0-0:i386 libatspi2.0-dev:i386 \
        libatk1.0-0:i386 gir1.2-atk-1.0:i386 libcairo-gobject2:i386 \
        libgdk-pixbuf2.0-0:i386 gir1.2-gdkpixbuf-2.0:i386 libglib2.0-0:i386 \
        libmount-dev:i386 libselinux1-dev:i386 libatk-bridge2.0-0:i386 \
        libatk1.0-0:i386 libcairo-gobject2:i386 libcolord2:i386 \
        libgdk-pixbuf2.0-0:i386 libglib2.0-0:i386 libharfbuzz0b:i386 \
        libjson-glib-1.0-0:i386 libpango-1.0-0:i386 libpangocairo-1.0-0:i386 \
        libpangoft2-1.0-0:i386 librest-0.7-0:i386 gir1.2-pango-1.0:i386 \
        libharfbuzz-dev:i386 libpango-1.0-0:i386 libpangocairo-1.0-0:i386 \
        libpangoft2-1.0-0:i386 libpangoxft-1.0-0:i386 libmount1:i386 \
        libselinux1:i386 libmount1:i386 libselinux1:i386 libpcre2-dev:i386 \
        libatk-bridge2.0-dev libatk1.0-dev libcairo2-dev libgdk-pixbuf2.0-dev \
        libglib2.0-dev libpango1.0-dev libpcre2-8-0:i386 libpcre2-posix2:i386 \
        libpcre2-8-0:i386 || true;
        sudo apt-get clean -y;
        sudo apt-get install -f;
        sudo dpkg --configure -a;

    - name: Show tools version
      run: |
        ${{matrix.cc}} --version;
        ${{matrix.cxx}} --version;
        make --version;
    - name: Build (Debug Mode)
      run: |
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}};
        make -j$(nproc) DEBUG_MODE=1;
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --gui;
        make -j$(nproc) DEBUG_MODE=1;
    - name: Build
      run: |
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}};
        make -j$(nproc);
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --gui;
        make -j$(nproc);
    - name: Build 32-bit (Debug Mode)
      run: |
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --32-bit;
        make -j$(nproc) DEBUG_MODE=1;
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --32-bit --gui;
        make -j$(nproc) DEBUG_MODE=1;
    - name: Build 32-bit
      run: |
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --32-bit;
        make -j$(nproc);
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --32-bit --gui;
        make -j$(nproc);
