name: Build Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++

    env:
      V: 1
      BAN_WARN: 1

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Add 32-bit repo
      run: |
        sudo dpkg --add-architecture i386;

    - name: Update repo
      run: |
        sudo apt-get update -y --fix-missing;

    - name: Install aptitude
      run: |
        sudo apt-get install -y aptitude;

    - name: Install tools
      run: |
        sudo aptitude install -y clang gcc g++ make gcc-multilib g++-multilib;
        sudo aptitude install -y libgtk-3-common libstdc++6:i386 libgtk-3-dev \
        libgtk-3-common:i386 libc6-dev-i386 libgtk-3-dev:i386 libc6:i386;

    - name: Show tools version
      run: |
        ${{matrix.cc}} --version;
        ${{matrix.cxx}} --version;
        make --version;
        i386 pkg-config --cflags --libs gtk+-3.0;
        false;

    - name: Build (Debug Mode)
      run: |
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}};
        make -j$(nproc) DEBUG_MODE=1;
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --gui;
        make -j$(nproc) DEBUG_MODE=1;

    - name: Build
      run: |
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}};
        make -j$(nproc);
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --gui;
        make -j$(nproc);

    - name: Build 32-bit (Debug Mode)
      run: |
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --32-bit;
        make -j$(nproc) DEBUG_MODE=1;
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --32-bit --gui;
        make -j$(nproc) DEBUG_MODE=1;

    - name: Build 32-bit
      run: |
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --32-bit;
        make -j$(nproc);
        make -j$(nproc) clean_all;
        ./configure --cc=${{matrix.cc}} --cxx=${{matrix.cxx}} --ld=${{matrix.cc}} --32-bit --gui;
        make -j$(nproc);
